apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: log-data-volume
  name: log-data-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}