apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: log-service
  name: log-service
  namespace: default
spec:
  replicas: 1 #CHANGE
  minReadySeconds: 30
  selector:
    matchLabels:
      app: log-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: log-service
    spec:
      imagePullSecrets:
        - name: regcredgitlab
      containers:
        - image: #CONTAINER_IMAGE_PATH_CHANGE_IT
          imagePullPolicy: Always #IfNotPresent
          name: log-service
          env:
          - name: RABBIT_HOST
            valueFrom:
              configMapKeyRef:
                key: RABBIT_HOST
                name: my-project-config
          volumeMounts:
          - mountPath: "/app/logs"
            name: log-data-volume
#          ports:
#            - name: liveness-port
#              containerPort: 8001
#          readinessProbe:
#            httpGet:
#              path: /
#              port: 8001
#            failureThreshold: 5
#            periodSeconds: 10
#            initialDelaySeconds: 60
#          livenessProbe:
#            httpGet:
#              path: /
#              port: 8001
#            failureThreshold: 5
#            periodSeconds: 10
#            initialDelaySeconds: 60
      restartPolicy: Always
      volumes:
      - name: log-data-volume
        persistentVolumeClaim:
          claimName: log-data-volume
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: log-service
  name: log-service
  namespace: default
spec:
  ports:
    - port: 8001 #CHANGE
      protocol: TCP
#      targetPort: 8001 #CHANGE
  selector:
    app: log-service